#!/usr/bin/env bash

set -e

#--------------------------------------------------------------
# functions
#--------------------------------------------------------------
banner() {
cat << EOF

#--------------------------------------------------------------
# $@
#--------------------------------------------------------------
EOF
}

#--------------------------------------------------------------
# execution
#--------------------------------------------------------------
rm -rf output
mkdir -p output
cd output

# on exit, send SIGTERM to all the processes in the foreground process group,
# this allows for a clean termination of the server
exit_clean=0
send_sigterm_to_process_group() {
  if ((exit_clean != 1)); then
    echo "Send SIGTERM to process group"
    kill -SIGTERM -$$
  fi
}
trap send_sigterm_to_process_group EXIT

# 1- clean server files
rm -rf .multisim

# 2- compile server
banner "Compile server"
g++ -o run_sw_server                        \
  -DMULTISIM_SW                             \
  -I${MULTISIM_SRC}/core                    \
  $MULTISIM_SRC/core/multisim_server.cpp    \
  $MULTISIM_SRC/core/socket_server/server.cpp \
  ../src/sw_server.cpp

# 3- compile client
banner "Compile client"
g++ -o run_sw_client                        \
  -DMULTISIM_SW                             \
  -I${MULTISIM_SRC}/core                    \
  $MULTISIM_SRC/core/multisim_client.cpp    \
  $MULTISIM_SRC/core/socket_server/client.cpp \
  ../src/sw_client.cpp

# 4- start server in background
banner "Start server"
./run_sw_server &
SERVER_PID=$!

# 5- start client (decide pass/fail)
banner "Start client"
./run_sw_client

# 6- cleanup
wait $SERVER_PID
exit_clean=1

echo ""
echo "Test completed successfully!"
