#!/bin/bash

set -e

cpu_index="$1"

output_dir=output_cpu_$cpu_index

mkdir -p $output_dir
cp -rfL src/* $output_dir
cd $output_dir

g++ -o libdpi.so -g -shared -fPIC             \
  -I${VCS_HOME}/include                       \
  $MULTISIM_SRC/core/multisim_client.cpp      \
  $MULTISIM_SRC/core/socket_server/client.cpp

vcs -q -full64 -sverilog                        \
  -ignore initializer_driver_checks             \
  -timescale=1ns/1ps                            \
  +define+MULTISIM_4STATE                       \
  cpu_multisim_client.sv cpu.sv                 \
  +incdir+$MULTISIM_SRC/core                    \
  $MULTISIM_SRC/core/multisim_client_push.sv    \
  $MULTISIM_SRC/core/multisim_client_pull.sv    \
  $MULTISIM_SRC/axi/multisim_client_axi_push.sv \
  > compile.log

./simv -sv_lib libdpi +CPU_INDEX=$cpu_index > sim.log
