#!/bin/bash

set -e

cpu_nb="$1"
[ "$cpu_nb" = "" ] && cpu_nb=4

mkdir -p output_top
cp -rfL src/* output_top
cd output_top

g++ -o libdpi.so -g -shared -fPIC             \
  -I${VCS_HOME}/include                       \
  $MULTISIM_SRC/core/multisim_server.cpp      \
  $MULTISIM_SRC/core/socket_server/server.cpp

vcs -q -full64 -sverilog                        \
  -ignore initializer_driver_checks             \
  -timescale=1ns/1ps                            \
  +define+MULTISIM                              \
  +define+MULTISIM_4STATE                       \
  top.sv memory.sv cpu_multisim_server.sv       \
  +incdir+$MULTISIM_SRC/core                    \
  $MULTISIM_SRC/core/multisim_server_push.sv    \
  $MULTISIM_SRC/core/multisim_server_pull.sv    \
  $MULTISIM_SRC/axi/multisim_server_axi_pull.sv \
  -pvalue+top.CPU_NB=$cpu_nb                    \
  > compile.log

./simv -sv_lib libdpi

$MULTISIM_SRC/bin/kill_all_clients
