#!/usr/bin/env bash

set -e

RUNTIME_DIR="$(readlink -e $(dirname $0))"


#--------------------------------------------------------------
# functions
#--------------------------------------------------------------
run_emu() {
  export LD_LIBRARY_PATH="$PWD:$LD_LIBRARY_PATH"
  cmd="velrun -c -emul $Emulator -sv_lib libdpi -do run.tcl"

  echo $cmd
  $cmd
}


#--------------------------------------------------------------
# execution
#--------------------------------------------------------------
cd $RUNTIME_DIR

# on exit, send SIGTERM to all the processes in the foreground process group,
# this allows for a clean termination of the clients
exit_clean=0
send_sigterm_to_process_group() {
  if ((exit_clean != 1)); then
    echo "Send SIGTERM to process group"
    kill -SIGTERM -$$
  fi
}
trap send_sigterm_to_process_group EXIT

# 1- clean server files
rm -rf .multisim

# 2- start server
run_emu &

# 3- start client (decide pass/fail)
./run_sw_test

 # leave time to velrun to exit
sleep 15
exit_clean=1
